name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - run: printenv
      - run: cat /home/runner/work/_temp/_github_workflow/event.json

